### ISSUE TITLE
Confirm on Close

### ISSUE THREAD

**Issue by Ravancloak** [bazzinotti/snestracker#63] opened 2020-06-13 20:42 UTC
A dialogue box asking to confirm on close would reduce the amount of lost work, I only lost an instrument but I'd imagine it could be worse.

**Comment by bazzinotti** [comment] 2020-06-27 08:00
#105 is a duplicate of this, but there's programming comments in there so I'm going to close this.

**Closed by bazzinotti** 2020-06-27 08:00 UTC
