### ISSUE TITLE
[bug] Incorrect volume on some instrument instances.

### ISSUE THREAD

**Issue by RowanDDR** [bazzinotti/snestracker#150] opened 2020-09-30 11:37 UTC
**To Reproduce**:
Kindly open the attached .sts song in SNES Tracker v0.2.1 (Windows 10 64bit): [Knight Moves v3.zip](https://github.com/bazzinotti/snestracker/files/5305103/Knight.Moves.v3.zip)
Then go to sequence 20, solo track 6 (drum) and start playing. You'll notice the first instance of the drum doesn't sound very loud. But as the pattern repeats (7 times in a row), its louder all the other times.

**Expected behavior**:
The volume of the drum should be the same in every instance, as its the same pattern, and I have not knowingly specified any volume change in the track itself.

I hope this git issue isn't a dupe!

**Comment by bazzinotti** [comment] 2020-10-17 01:58
Rowan, I know this is a really scary place... there's a lot of people out there laughing in the shadows!!!!   but, I came all this way to tell you,,,,,, this is just a dupe of #104 💇‍♂️

**Closed** 2020-10-17 16:01 UTC
Labels: bug
